//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Vulnerabilities.Schema
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Rules for custom properties
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Properties
    {

    }

    /// <summary>
    /// A dictionary captures a set of key/value pairs
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Dictionary : System.Collections.Generic.Dictionary<string, Anonymous>
    {

    }

    /// <summary>
    /// The Hashes type represents one or more cryptographic hashes, as a special set of key/value pairs
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class HashesType : System.Collections.Generic.Dictionary<string, Anonymous>
    {

    }

    /// <summary>
    /// External references are used to describe pointers to information represented outside of STIX.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class ExternalReference
    {
        /// <summary>
        /// A human readable description
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>
        /// A URL reference to an external resource.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("url")]
        public System.Uri Url { get; set; }

        /// <summary>
        /// Specifies a dictionary of hashes for the file.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("hashes")]
        public Hashes Hashes { get; set; }



        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// The granular-marking type defines how the list of marking-definition objects referenced by the marking_refs property to apply to a set of content identified by the list of selectors in the selectors property.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class GranularMarking
    {
        /// <summary>
        /// A list of selectors for content contained within the STIX object in which this property appears.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("selectors")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public System.Collections.Generic.ICollection<string> Selectors { get; set; } = new System.Collections.ObjectModel.Collection<string>();

        /// <summary>
        /// Identifies the language of the text identified by this marking.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("lang")]
        public string Lang { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("marking_ref")]
        [System.ComponentModel.DataAnnotations.Required]
        public Marking_ref Marking_ref { get; set; }



        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum ExtensionTypeEnum
    {

        [System.Runtime.Serialization.EnumMember(Value = @"new-sdo")]
        NewSdo = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"new-sco")]
        NewSco = 1,


        [System.Runtime.Serialization.EnumMember(Value = @"new-sro")]
        NewSro = 2,


        [System.Runtime.Serialization.EnumMember(Value = @"property-extension")]
        PropertyExtension = 3,


        [System.Runtime.Serialization.EnumMember(Value = @"toplevel-property-extension")]
        ToplevelPropertyExtension = 4,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Extension : Properties
    {
        /// <summary>
        /// The type of extension.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("extension_type")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public ExtensionTypeEnum Extension_type { get; set; }



        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Common properties and behavior across all STIX Domain Objects and STIX Relationship Objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Core : Properties
    {
        /// <summary>
        /// The type property identifies the type of STIX Object (SDO, Relationship Object, etc). The value of the type field MUST be one of the types defined by a STIX Object (e.g., indicator).
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(250, MinimumLength = 3)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^([a-z][a-z0-9]*)+(-[a-z0-9]+)*\-?$")]
        public string Type { get; set; }

        /// <summary>
        /// The version of the STIX specification used to represent this object.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("spec_version")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public CoreSpec_version Spec_version { get; set; }

        /// <summary>
        /// The id property universally and uniquely identifies this object.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^[a-z][a-z0-9-]+[a-z0-9]--[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$")]
        public string Id { get; set; }

        /// <summary>
        /// The ID of the Source object that describes who created this object.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("created_by_ref")]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^[a-z][a-z0-9-]+[a-z0-9]--[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$")]
        public string Created_by_ref { get; set; }

        /// <summary>
        /// The labels property specifies a set of terms used to describe this object.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("labels")]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public System.Collections.Generic.ICollection<string> Labels { get; set; }

        /// <summary>
        /// The created property represents the time at which the first version of this object was created. The timstamp value MUST be precise to the nearest millisecond.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("created")]
        [System.ComponentModel.DataAnnotations.Required]
        public Created Created { get; set; }

        /// <summary>
        /// The modified property represents the time that this particular version of the object was modified. The timstamp value MUST be precise to the nearest millisecond.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("modified")]
        [System.ComponentModel.DataAnnotations.Required]
        public Modified Modified { get; set; }

        /// <summary>
        /// The revoked property indicates whether the object has been revoked.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("revoked")]
        public bool Revoked { get; set; }

        /// <summary>
        /// Identifies the confidence that the creator has in the correctness of their data.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("confidence")]
        [System.ComponentModel.DataAnnotations.Range(0, 100)]
        public int Confidence { get; set; }

        /// <summary>
        /// Identifies the language of the text content in this object.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("lang")]
        public string Lang { get; set; }

        /// <summary>
        /// A list of external references which refers to non-STIX information.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("external_references")]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public System.Collections.Generic.ICollection<External_references> External_references { get; set; }

        /// <summary>
        /// The list of marking-definition objects to be applied to this object.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("object_marking_refs")]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public System.Collections.Generic.ICollection<string> Object_marking_refs { get; set; }

        /// <summary>
        /// The set of granular markings that apply to this object.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("granular_markings")]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public System.Collections.Generic.ICollection<GranularMarking> Granular_markings { get; set; }

        /// <summary>
        /// Specifies any extensions of the object, as a dictionary.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("extensions")]
        public System.Collections.Generic.IDictionary<string, object> Extensions { get; set; }



        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// A Vulnerability is a mistake in software that can be directly used by a hacker to gain access to a system or network.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Vulnerability : Core
    {
        /// <summary>
        /// The type of this object, which MUST be the literal `vulnerability`.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public VulnerabilityType Type { get; set; }


        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public object Id { get; set; }

        /// <summary>
        /// The name used to identify the Vulnerability.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// A description that provides more details and context about the Vulnerability.
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string Description { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Anonymous
    {


        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Marking_ref : string
    {

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum CoreSpec_version
    {

        [System.Runtime.Serialization.EnumMember(Value = @"2.0")]
        _2_0 = 0,


        [System.Runtime.Serialization.EnumMember(Value = @"2.1")]
        _2_1 = 1,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Created : string
    {

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Modified : string
    {

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Anonymous2 : Properties
    {


        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public enum VulnerabilityType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"vulnerability")]
        Vulnerability = 0,


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.0.0.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Hashes : System.Collections.Generic.Dictionary<string, string>
    {


        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }
}